### ISSUE TITLE
13. As a user, I want the app to have a user friendly layout on my List.js

### ISSUE THREAD

**Issue by fullybaked** [the-collab-lab/tcl-56-smart-shopping-list#13]
## Summary

Currently the app does not include much styling. The user should be welcomed by a clear, easy to use, and visually appealing layout. 

## Acceptance criteria

- [ ] Install Tailwind as a dependency. [TailwindCSS](https://tailwindcss.com/)
- [ ] Create simple wireframe using a whiteboard to determine layout of List.js
- [ ] Implement layout design in List.js, AddItem, and Home pages using Tailwind utility classes.

**Comment by drakenguyen4000** [comment]
Hey Team, [wireframe ](https://miro.com/app/board/uXjVOq136Vg=/?share_link_id=247154006654)for the List Items page is up.

**Comment by yiremorlans** [comment]
PR #33 closes this issue
