### ISSUE TITLE
As a user, I want to make Chippy a component and have him handle messages

### ISSUE THREAD

**Issue by drakenguyen4000** [the-collab-lab/tcl-56-smart-shopping-list#37]
## Summary 
Turn Chippy into it's own component to handle messages in the app.  

## Acceptance Criteria
- [ ] Make Chippy as it's own component.
- [ ] Add Chippy to Add Item and Home pages to handle messages.  
- [ ] Update old Chippy setup with new Chippy component in List page.

**Comment by yiremorlans** [comment]
PR #38 closes this issue
